name: Make Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --release --verbose

      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/steam-icon-recovery
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
