name: Rust

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --release --verbose

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: steam-icon-recovery
          path: target/release/steam-icon-recovery

  release:

    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: steam-icon-recovery

      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          files: steam-icon-recovery/steam-icon-recovery
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
